### ISSUE TITLE
Parsing: "No config in {model_path}"

### ISSUE THREAD

**Issue by RZiane** [hopsparser/hopsparser#70]
Hi Loic, 

I have a problem with the parsing command. Using the model UD_Old_French-SRCMF-2.9-flaubert+fro available here: https://github.com/hopsparser/hopsparser/blob/main/docs/models.md

I get the error "No config in {model_path}". I tried to change the file name to config.yaml. Then the script returns an error that the vocab.lst file is missing. 

With an old version of the Old French model (from approximately last october), the command works fine, which is to be expected considering its content below: 
![Capture d’écran de 2022-05-10 18-56-26](https://user-images.githubusercontent.com/77019730/167675797-67ad0228-7f21-4e0a-a0ed-74332b32edda.png)

So it could be related to the parsing script version but that may be a wrong use by me.

Hope you could help us solving this issue. 

Thanks in advance, 
Rayan

**Comment by LoicGrobol** [comment]
@RZiane Did you get a chance to try it?

**Comment by RZiane** [comment]
Sorry, I forgot to reply, the new version has solved the issue.

**Comment by LoicGrobol** [comment]
Great! Thank you!
