### ISSUE TITLE
Broken models links in documentation page

### ISSUE THREAD

**Issue by RZiane** [hopsparser/hopsparser#91]
Hi Loïc, 
The two links for these highlighted models are broken: 

![image](https://user-images.githubusercontent.com/77019730/225690910-08a62dad-03e1-43c1-b12d-45c7e4f776f6.png)

**Comment by LoicGrobol** [comment]
This should be closed by [6e4e384](https://github.com/hopsparser/hopsparser/commit/6e4e3842e125b45a96c3f0ea3224ec812ee56b75). The links at <https://hopsparser.readthedocs.io/en/latest/models.html> should work now.
